application: jsongae
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.jar$

handlers:

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /client
  static_dir: client

- url: /css
  static_dir: css

- url: /images/(.*\.(gif|jpg|png))
  static_files: images/\1
  upload: images/(.*\.(gif|jpg|png))
  expiration: 5h

- url: /rpc
  script: app.py

- url: /
  script: app.py
